export enum actionTypes {

  // Package List Fetch States
  FETCH_PACKAGE_LIST_REQUEST = 'FETCH_PACKAGE_LIST_REQUEST',
  FETCH_PACKAGE_LIST_SUCCESS = 'FETCH_PACKAGE_LIST_SUCCESS',
  FETCH_PACKAGE_LIST_FAILURE = 'FETCH_PACKAGE_LIST_SUCCESS',

  // Package Fetch States
  FETCH_PACKAGE_REQUEST = 'FETCH_PACKAGE_REQUEST',
  FETCH_PACKAGE_SUCCESS = 'FETCH_PACKAGE_SUCCESS',
  FETCH_PACKAGE_FAILURE = 'FETCH_PACKAGE_SUCCESS',

  // Packages
  UPDATE_PACKAGE_LIST = 'UPDATE_PACKAGE_LIST',
  UPDATE_CURRENT_PACKAGE_VIEW = 'UPDATE_CURRENT_PACKAGE_VIEW',

  // Author Fetch States
  FETCH_CURRENT_AUTHOR_REQUEST = 'FETCH_CURRENT_AUTHOR_REQUEST',
  FETCH_CURRENT_AUTHOR_SUCCESS = 'FETCH_CURRENT_AUTHOR_SUCCESS',
  FETCH_CURRENT_AUTHOR_FAILURE = 'FETCH_CURRENT_AUTHOR_SUCCESS',
  // Authors
  UPDATE_CURRENT_AUTHOR_VIEW = 'UPDATE_CURRENT_AUTHOR_VIEW',
}